version: '3.8'  

services:
  csvserver:
    image: infracloudio/csvserver   
    container_name: csvserver       
    ports:
      - "9393:9300"                 
    volumes:
      - /root/csvserver/solution/inputFile:/csvserver/inputdata  
    env_file:
      - ./csvserver.env    
    restart: unless-stopped        
